@BookingApi_HostAddress = http://localhost:5252

GET {{BookingApi_HostAddress}}/weatherforecast/
Accept: application/json

###

### Register a new user
POST {{BookingApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "noah",
  "password": "test123"
}

###

### Login
POST {{BookingApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "noah",
  "password": "test123"
}

###

### Try creating a customer WITHOUT logging in (should fail)
POST {{BookingApi_HostAddress}}/api/customers
Content-Type: application/json

{
  "name": "Test Testsson",
  "email": "test@test.com"
}

###
